---

- name: file module
  hosts: all
  gather_facts: no

  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /home/fourth/test
        state: directory
    
    - name: copy files from local to remote
      copy: 
        src: files/test.txt
        dest: /home/fourth/test/test.txt